using System.Reflection;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Shotgun.Testing;

// Generic in-process ASP.NET Core host for E2E-testing any Shotgun<TEntity, TRepository, TId>
// controller. Deliberately bypasses WebApplicationFactory's default entry-point resolution
// (there is no Program.cs for the controller under test) by building the IHostBuilder from
// scratch. TEntryPoint must be a type from the *consuming* test assembly — WebApplicationFactory
// needs an assembly with an actual entry point to locate the host's deps.json, and an xunit test
// project has one (generated by the test SDK), whereas this library assembly does not. Any type
// in that assembly works; it is only used to resolve the assembly.
public class ShotgunWebApplicationFactory<TEntryPoint> : WebApplicationFactory<TEntryPoint>
    where TEntryPoint : class
{
    private readonly Action<IServiceCollection> _configureServices;
    private readonly Assembly _controllerAssembly;

    public ShotgunWebApplicationFactory(Action<IServiceCollection> configureServices, Assembly? controllerAssembly = null)
    {
        _configureServices = configureServices;
        _controllerAssembly = controllerAssembly ?? typeof(TEntryPoint).Assembly;
    }

    protected override IHostBuilder CreateHostBuilder()
    {
        return Host.CreateDefaultBuilder()
            .ConfigureWebHost(webBuilder =>
            {
                webBuilder.UseTestServer();
                webBuilder.ConfigureServices(services =>
                {
                    services.AddControllers().AddApplicationPart(_controllerAssembly);
                    _configureServices(services);
                });
                webBuilder.Configure(app =>
                {
                    app.UseRouting();
                    app.UseEndpoints(endpoints => endpoints.MapControllers());
                });
            });
    }
}
